# Generated by Django 3.1.2 on 2020-12-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donasi', '0015_auto_20201120_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donasi',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='media/img/'),
        ),
    ]
