# Generated by Django 3.1.2 on 2020-12-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donasi', '0016_auto_20201231_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donasi',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
